# Use custom format:
format="$directory$time$git_branch$nodejs$lua$character"

right_format="$memory_usage"

# Prompt symbols
[character]
success_symbol = "[ğŸˆ](#a6e3a1 bold)"
error_symbol = "[ğŸˆ](#f38ba8)"
vicmd_symbol = "[ğŸˆ](#f9e2af)"

[directory]
format = "[î‚¶]($style)[(fg:#49628a)ï„” $path](bg:#89b4fa fg:#49628a)[î‚´ ]($style)"
style = "fg:#89b4fa"

[git_branch]
format = "[î‚¶]($style)[[ï˜ ](bg:#89b4fa fg:#49628a bold)$branch](bg:#89b4fa fg:#4c4f69)[î‚´ ]($style)"
style = "fg:#89b4fa"


[nodejs]
format = "[î‚¶]($style)[[ó°™ ](bg:#89b4fa fg:#49628a bold)$version](bg:#89b4fa fg:#4c4f69)[î‚´ ]($style)"
style = "fg:#89b4fa"

[lua]
format = "[î‚¶]($style)[[ó°¢± ](bg:#89b4fa fg:#49628a bold)$version](bg:#89b4fa fg:#4c4f69)[î‚´ ]($style)"
style = "fg:#89b4fa"

[memory_usage]
format = "[î‚¶]($style)[[ó°¢± ](bg:#89b4fa fg:#49628a bold)$ram](bg:#89b4fa fg:#4c4f69)[î‚´ ]($style)"
style = "fg:#89b4fa"

